version: "3"
services:
  webserver:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: webserver
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - .:/app
    env_file:
      - ./.env