name: Node.js CI-CD

on:
  push:
    branches: [ "production-branch" ]
  pull_request:
    branches: [ "production-branch" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: node --version
    - name: Set up environment variables
      run: |
        echo "MY_ENV_VARIABLE=${{ secrets.ENV_FILE }}" >> .env
        echo .env
        cat .env
    - run: npm install
    
    # Deployment step
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.EC2_PUBLIC_IP}}
        username: ubuntu
        key: ${{secrets.EC2_SSH_KEY}}
        script: |
          echo "Connected to AWS EC2 instance"
          # Add the necessary deployment commands here
          cd ExpressJs-Ecommerce-webdev-project-1
          git pull
          sudo pm2 reload all
